"""add phone number

Revision ID: 39b42f084294
Revises: d846f9423f81
Create Date: 2024-04-10 18:59:05.553537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39b42f084294'
down_revision: Union[str, None] = 'd846f9423f81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# 149.) So we added the phone number column in this revision and it autogenerated the "upgrade" function.
#   And so the only thing else we have to do is do an: "alembic upgrade head", and it's going to push out
#   those changes. So let's refresh and let's just double check. We can see "phone number" column is now set.

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###

# 150.) And it also autogenerated the "downgrade" function so that we can undo the changes that is intended for (149)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
